export const phones = [
    {
        id: 0,
        name: 'Nokia 3310',
        description: 'Телефон, переживший падение в жерло вулкана',
        url: 'https://cdn.dlvry.ru/upload/iblock/5d7/0v4a6338_2.jpg',
        price: 800,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 1,
        name: 'Iphone 7',
        description: 'Не знаю, что про него написать. Но здесь должно быть что-то неописуемо интересное',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        price: 32000,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 2,
        name: 'Samsung m51',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Здесь должно быть завораживающее воображение описание, из-за которого просыпается желание купить телефон',
        price: 35000,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 3,
        name: 'Ролл Филадельфия с лососем и крабом',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        weight: 290,
        nameCategoryRu: 'холодные',
        category: 'rolls'
    },
    {
        id: 4,
        name: 'Ролл Филадельфия с лососем',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        category: 'rolls',
        weight: 290,
        nameCategoryRu: 'холодные',
    },
    {
        id: 5,
        name: 'Ролл Филадельфия с лососем',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        category: 'rolls',
        weight: 290,
        nameCategoryRu: 'холодные',
    },
    {
        id: 6,
        name: 'Nokia 3310',
        description: 'Телефон, переживший падение в жерло вулкана',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        price: 800,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 7,
        name: 'Iphone 7',
        description: 'Не знаю, что про него написать. Но здесь должно быть что-то неописуемо интересное',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        price: 32000,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 8,
        name: 'Samsung m51',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Здесь должно быть завораживающее воображение описание, из-за которого просыпается желание купить телефон',
        price: 35000,
        weight: 290,
        category: 'rolls'
    },
    {
        id: 9,
        name: 'Ролл Филадельфия с лососем и крабом',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        category: 'rolls',
        weight: 290,
        nameCategoryRu: 'холодные',
    },
    {
        id: 10,
        name: 'Ролл Филадельфия с лососем',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        category: 'pizza',
        weight: 290,
        nameCategoryRu: 'холодные',
    },
    {
        id: 11,
        name: 'Ролл Филадельфия с лососем',
        url: 'https://dlvry.ru/upload/iblock/062/0v4a6391_2.jpg',
        description: 'Филе лосося, сливочный сыр, огурец, рис, нори, чернила каракатицы, соус тонкацу.',
        price: 490,
        category: 'pizza',
        weight: 290,
        nameCategoryRu: 'холодные',
    }
];